### PR TITLE
New index.html design

### PR DESCRIPTION
**Pull request by wlabarron**
I've revised `index.html` to another design. I've left a lot of other files in the repo untouched -- I'm not sure if they need to stay or can be removed. The file doesn't have any dependencies.

### CODE REVIEW

**Comment by minorDeveloper** [comment]
All other files can be removed. The project was quickly created from a default webstorm HTML 5 template.

**Review by minorDeveloper — CHANGES_REQUESTED** [review]
This looks great and I like the aesthetic. Certainly more readable.

Would it be possible to get the current logo in the top right? (Probably not visible at all on small devices).

**Comment by wlabarron** [comment]
Can do, but it would add 13KB. Is that too much?

**Comment by wlabarron** [comment]
Also, related to me fixing #6 and as a usability thing -- what do you think of a different save button for each config panel? Would that work with how you've currently implemented the backend?

**Comment by minorDeveloper** [comment]
> Also, related to me fixing #6 and as a usability thing -- what do you think of a different save button for each config panel? Would that work with how you've currently implemented the backend?

That would be entirely fine. The backend looks through the request to check for certain members and only updates the ones that are found:

`if (request->hasParam("showID", true)) {
    config.showID = request->getParam("showID", true)->value().toInt();
    cti.setShowID(config.showID);
  }`

**Comment by minorDeveloper** [comment]
This all looks wonderful, thank you so much.

**Pull request merged**
